### ISSUE TITLE
block reference should not nested with styles, like font size, header, etc

### ISSUE THREAD

**Issue by XinLi0111** [rcvd/logseq-bear-theme#19]
this problem was fixed in logseq default theme in #2469.
![image](https://user-images.githubusercontent.com/31495943/146631265-dc282825-1417-4303-9b7b-9630a9f30455.png)
![image](https://user-images.githubusercontent.com/31495943/146631286-494f9362-272f-48d8-9c1a-eecf41d29532.png)

**Comment by XinLi0111** [comment]
https://github.com/logseq/logseq/issues/2469

**Comment by rcvd** [comment]
I think I don't really understand the issue here. Could you please try to explain the current and the expected behaviour a bit more?

**Comment by XinLi0111** [comment]
This is what I expected:
![image](https://user-images.githubusercontent.com/31495943/146632219-ca993018-dcf7-428c-b26a-ed839a86c9f7.png)

**Comment by rcvd** [comment]
I understand now but I'm not sure that this would be something that everyone else would expect - especially when we are talking about inline formats like bold or highlight. Maybe you have a block of text where you marked the most important parts - do you really want that to be not included in the mirrored block? However, I can see why you maybe don't want to be the header sizes.

**Comment by XinLi0111** [comment]
Thanks for your reply. 

This issue was solved in default theme, refer to: https://github.com/logseq/logseq/issues/3516
![image](https://user-images.githubusercontent.com/31495943/146640699-9cc6a671-efba-4ac7-991f-21bdf8441c2d.png)

But the custom css not worked in Bear theme,  do you have any suggestions?

**Comment by rcvd** [comment]
You can modify your `custom.css`-page like this:

``` css
@import url('https://rcvd.github.io/logseq-bear-theme/bear.css');

/* Everything below this line will override the settings in the bear theme */
.block-content.inline h1 {
  font-weight: normal;
}
```
