### ISSUE TITLE
The theme doesnt apply to the tripple-dot menu

### ISSUE THREAD

**Issue by m1karii** [rcvd/logseq-bear-theme#33]
![image](https://user-images.githubusercontent.com/82673417/190604518-91749ef2-a0e3-4a30-99b4-b3cf4edc1e81.png)

**Comment by borutmrak** [comment]
I managed to fix this with this in custom.css:

```css
div.menu-links-wrapper {
background-color: transparent;
};
```

should be fixed the proper way (with another selector probably) in the theme.
