### ISSUE TITLE
Please fix the bug of new-page button from left sidebar

### ISSUE THREAD

**Issue by poisonoff** [rcvd/logseq-bear-theme#35]
Thanks!
![Screenshot 2023-01-06 at 10 57 56 PM](https://user-images.githubusercontent.com/31033194/211107032-355de103-07c7-45e9-8da4-dfcda72071e1.jpg)

**Comment by borutmrak** [comment]
Mine is a little different (using dark mode). It inherits the default green color of logseq. I was able to fix everything around the button with this:

```css
.left-sidebar-inner .create {
  background-image: linear-gradient(transparent, var(--cl-bunker));
};
```
Still no gradient, probably because the container around it has a background set. Maybe this could be replaced with background-image: transparent.

I can't change the button though, problem is that there is background-color set with !important from the logseq builtin style.css, no matter what selector I use I can't override that it seems.
