### ISSUE TITLE
Line Numbers in code blocks overlapping text

### ISSUE THREAD

**Issue by diva-D** [rcvd/logseq-bear-theme#41]
I encountered an issue with the theme where the line numbers in a code block are not styled properly. They overlap the code content and don't sit properly on the left side of the code block

![2024-06-06_12-59-21_Logseq_File logseqconfig edn](https://github.com/rcvd/logseq-bear-theme/assets/28694272/9b4ec342-481c-4bca-ab80-7c0ee95b0165)

**Steps to reproduce:**
1.	Open a code block in Logseq with the Bear theme applied.
1.	Notice that the line numbers are not styled correctly, making it difficult to read and differentiate from the code content.

**Expected Behavior:**
The line numbers and code "gutter" should be properly left aligned, so they don't overlap the code content

**Actual Behavior:**
The line numbers appear unstyled or improperly styled, blending with the code content and causing readability issues.

**Additional Information:**
  - Logseq version: 0.10.9
  - Theme version: 0.0.37

**Comment by miaoyang129** [comment]
I encounter the same problem, have you got any solution?

**Comment by miaoyang129** [comment]
I tried to fix this problem with GPT but failed, at last I found an alternative solution: disable the code block line number. If you don't mind the absence of line number, you can add the following code to your 'custom.css':

```css
/* --- Disable line numbers cleanly in all code blocks --- */
.extensions__code .CodeMirror-gutters,
.extensions__code .cm-gutters,
.extensions__code .CodeMirror-linenumber,
.extensions__code .cm-lineNumbers {
  display: none !important;
  width: 0 !important;
}

/* Adjust code content to fill full width */
.extensions__code .CodeMirror-lines,
.extensions__code .cm-content {
  margin-left: 0 !important;
}
```

After this modification, you get the following interface:

<img width="710" height="691" alt="Image" src="https://github.com/user-attachments/assets/f53c00b9-b4a3-4160-92d1-1f9a666755c3" />
